name: Compress Images

on:
  push:
    branches:
      - main
    paths:
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install imagemin-cli
        run: npm install -g imagemin-cli imagemin-mozjpeg imagemin-pngquant

      - name: Compress images
        run: |
          mkdir -p compressed
          find . -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \) \
          -exec imagemin {} --plugin=mozjpeg --plugin=pngquant > compressed/{} \;

      - name: Move compressed images back
        run: rsync -a --remove-source-files compressed/ ./

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Optimized images"
