name: Compress images (in-place + webp)

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.png"
  pull_request:
    branches: [ main ]
    paths:
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.png"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick pngquant webp

      - name: Optimize JPG/JPEG in place
        shell: bash
        run: |
          shopt -s globstar nullglob nocaseglob
          files=(**/*.jpg **/*.jpeg)
          if ((${#files[@]})); then
            mogrify -auto-orient -strip -resize '1920x1920>' -quality 85 "${files[@]}"
          else
            echo "No JPG/JPEG files found."
          fi

      - name: Optimize PNG in place
        shell: bash
        run: |
          shopt -s globstar nullglob nocaseglob
          for f in **/*.png; do
            [ -f "$f" ] || continue
            pngquant --force --skip-if-larger --quality=65-85 --ext .png "$f"
          done

      - name: Create WebP copies
        shell: bash
        run: |
          shopt -s globstar nullglob nocaseglob
          for f in **/*.jpg **/*.jpeg **/*.png; do
            [ -f "$f" ] || continue
            cwebp -quiet -q 80 "$f" -o "${f%.*}.webp"
          done

      - name: Commit optimized images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: optimize images (in-place + webp)"
          file_pattern: "**/*.{jpg,jpeg,png,webp}"
